services:
  hotwire-sample:
    container_name: hotwire-sample
    build: .
    volumes:
      - .:/app
    command: sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
